### ISSUE TITLE
Yiisoft\Di\NotFoundException No definition or class found or resolvable for "Yiisoft\Hydrator\HydratorInterface" while building "Yiisoft\Form\FormHydrator" -> "Yiisoft\Hydrator\HydratorInterface".

### ISSUE THREAD

**Issue by rossaddison** [rossaddison/yii3-i#73]
### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.2.1
| Operating system | Windows 10

**Comment by rossaddison** [comment]
Yiisoft\Di\NotFoundException: No definition or class found or resolvable for "Yiisoft\Hydrator\HydratorInterface" while building "Yiisoft\Form\FormHydrator" -> "Yiisoft\Hydrator\HydratorInterface". in /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/di/src/Container.php:533
Stack trace:
#0 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/di/src/Container.php(497): Yiisoft\Di\Container->buildInternal('Yiisoft\\Form\\Fo...')
#1 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/di/src/Container.php(140): Yiisoft\Di\Container->build('Yiisoft\\Form\\Fo...')
#2 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/injector/src/Injector.php(309): Yiisoft\Di\Container->get('Yiisoft\\Form\\Fo...')
#3 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/injector/src/Injector.php(290): Yiisoft\Injector\Injector->resolveObjectParameter(Object(Yiisoft\Injector\ResolvingState), 'Yiisoft\\Form\\Fo...', false)
#4 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/injector/src/Injector.php(255): Yiisoft\Injector\Injector->resolveNamedType(Object(Yiisoft\Injector\ResolvingState), Object(ReflectionNamedType), false)
#5 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/injector/src/Injector.php(195): Yiisoft\Injector\Injector->resolveParameterType(Object(Yiisoft\Injector\ResolvingState), Object(ReflectionNamedType), false, NULL)
#6 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/injector/src/Injector.php(154): Yiisoft\Injector\Injector->resolveParameter(Object(ReflectionParameter), Object(Yiisoft\Injector\ResolvingState))
#7 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/injector/src/Injector.php(68): Yiisoft\Injector\Injector->resolveDependencies(Object(ReflectionFunction), Array)
#8 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareFactory.php(271): Yiisoft\Injector\Injector->invoke(Object(Closure), Array)
#9 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(93): Psr\Http\Server\MiddlewareInterface@anonymous->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#10 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/rate-limiter/src/LimitRequestsMiddleware.php(47): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#11 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(93): Yiisoft\Yii\RateLimiter\LimitRequestsMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#12 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/data-response/src/Middleware/FormatDataResponse.php(29): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#13 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(93): Yiisoft\DataResponse\Middleware\FormatDataResponse->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#14 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/csrf/src/CsrfMiddleware.php(48): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#15 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(93): Yiisoft\Csrf\CsrfMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#16 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(49): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#17 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareDispatcher.php(48): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#18 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/router/src/MatchingResult.php(112): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#19 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/router/src/Middleware/Router.php(59): Yiisoft\Router\MatchingResult->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#20 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(93): Yiisoft\Router\Middleware\Router->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#21 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/yii-middleware/src/Locale.php(111): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#22 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(93): Yiisoft\Yii\Middleware\Locale->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#23 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/user/src/Login/Cookie/CookieLoginMiddleware.php(71): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#24 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(93): Yiisoft\User\Login\Cookie\CookieLoginMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#25 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/cookies/src/CookieMiddleware.php(84): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#26 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(93): Yiisoft\Cookies\CookieMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#27 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/session/src/SessionMiddleware.php(36): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#28 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(93): Yiisoft\Session\SessionMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#29 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/yii-sentry/src/SentryMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#30 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(93): Yiisoft\Yii\Sentry\SentryMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#31 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/error-handler/src/Middleware/ErrorCatcher.php(124): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#32 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(93): Yiisoft\ErrorHandler\Middleware\ErrorCatcher->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#33 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareStack.php(49): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#34 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/middleware-dispatcher/src/MiddlewareDispatcher.php(48): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#35 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/yii-http/src/Application.php(77): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#36 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/vendor/yiisoft/yii-runner-http/src/HttpApplicationRunner.php(140): Yiisoft\Yii\Http\Application->handle(Object(HttpSoft\Message\ServerRequest))
#37 /customers/d/f/7/yii3i.co.uk/httpd.www/yii3i/public/index.php(40): Yiisoft\Yii\Runner\Http\HttpApplicationRunner->run()
#38 {main}

**Comment by rossaddison** [comment]
This error is occurring on shared hosting test website yii3i.co.uk for some reason and it is most likely an oversight of mine.

**Comment by rossaddison** [comment]
It was an oversight of mine. I forgot to copy across the .merge-plan into the invoice/config directory.
